import os
import glob
import re
import pandas as pd
from datetime import datetime
from utils.general_utils import save_json_safe, extract_analysis, generate_explanation_report_txt
from utils.fairness_module import group_fairness
from utils.message_types import Message
from utils.prompt_library import PROMPTS
from utils.decision_mapping import DECISION_MAP_EXPLANATION, ROUTING_MAP_EXPLANATION
from agents.base_agent import BaseAgent
from utils.tcav_module import run_tcav_analysis


class ExplanationAgent(BaseAgent):
    def __init__(self, name="explanation", shared_llm=None, system_prompt=None, hub=None):
        super().__init__(name)
        self.llm = shared_llm
        self.system_prompt = system_prompt
        self.hub = hub
    
    @staticmethod
    def load_latest_prediction_df(folder="data/preds"):
        """
        Load the most recent prediction DataFrame from a directory.
        The function searches for CSV files following the naming convention `df_predictions_*.csv`.
        It assumes that filenames are timestamped and returns the most recent one.

        Args:
            folder (str, optional): Directory path to search for prediction files.

        Returns:
            pandas.DataFrame (containing the latest model predictions)
        """
        # Find all prediction files
        df_files = glob.glob(os.path.join(folder, "df_predictions_*.csv"))

        # Check that files exist
        if not df_files:
            raise FileNotFoundError(f"No prediction df found in folder: {folder}")

        # Sort files by date descending (latest first)
        df_files.sort(reverse=True)

        # Take the latest file
        latest_df_file = df_files[0]

        latest_df_preds = pd.read_csv(latest_df_file)

        return latest_df_preds 

    def _extract_score(self, llm_text: str) -> str:
        """
        The function parses the LLM output for a standardized decision token
        indicating the severity of detected issues.

        Extraction rules:
        1. Prefer a strict match where the decision appears on its own line.
        2. Fall back to a tolerant match anywhere in the text.
        3. Return a neutral fallback value if no valid score is detected.

        Args:
            llm_text (str): Raw text output generated by the LLM containing the scoring decision

        Returns:
            str: normalized issue severity score
        """
        SCORE_MAP = {
            "NO_ISSUES": "no issues",
            "MINOR_ISSUES": "minor issues",
            "SEVERE_ISSUES": "severe issues",
        }

        text = llm_text

        # Prefer explicit "Decision:" on its own line
        m = re.search(
            r'^\s*Decision\s*:\s*(NO_ISSUES|MINOR_ISSUES|SEVERE_ISSUES)\s*$',
            text,
            flags=re.IGNORECASE | re.MULTILINE
        )
        if m:
            SCORE_MAP.get(m.group(1).upper(), "none")
     
        # Tolerant match anywhere
        m2 = re.search(
            r'Decision\s*:\s*(NO_ISSUES|MINOR_ISSUES|SEVERE_ISSUES)',
            text,
            flags=re.IGNORECASE
        )
        if m2:
            SCORE_MAP.get(m2.group(1).upper(), "none")
            # decision = m2.group(1).upper()
            # return {"NO_ISSUES": "no issues", "MINOR_ISSUES": "minor issues", "SEVERE_ISSUES": "severe issues"}[decision]

        # Fallback
        return "none"
    
    def _extract_decision(self, llm_text: str) -> str:
        """
        Extract the final review decision from an LLM-generated text response.
        The function looks for a standardized decision token produced by the LLM and maps it to an internal, 
        normalized decision label used by the workflow router.

        The extraction rules:
        1. Prefer a strict match where the decision appears on its own line.
        2. Fall back to a more tolerant match anywhere in the text to handle minor formatting variations.
        3. Default to "abort" if no valid decision can be reliably extracted.

        Args:
            llm_text (str): Raw text output generated by the LLM for the review decision layer

        Returns:
            str: normalized decision label
        """
        text = llm_text

        # Prefer explicit "Decision:" on its own line
        m = re.search(
            r'^\s*Decision\s*:\s*(APPROVE|MINOR_ISSUES|REQUEST_RECLEAN|REQUEST_RETRAIN|ABORT)\s*$',
            text,
            flags=re.IGNORECASE | re.MULTILINE
        )
        if m:
            return DECISION_MAP_EXPLANATION.get(m.group(1).upper(), "minor_issues")

        # Tolerant match anywhere
        m2 = re.search(
            r'Decision\s*:\s*(APPROVE|MINOR_ISSUES|REQUEST_RECLEAN|REQUEST_RETRAIN|ABORT)',
            text,
            flags=re.IGNORECASE
        )
        if m2:
            return DECISION_MAP_EXPLANATION.get(m2.group(1).upper(), "minor_issues")

        # Fallback
        return "minor_issues"

    # ---------------------------
    # Main handler
    # ---------------------------
    def handle_message(self, message):
        print(f"[{self.name}] Explaining results...")

        metadata = message.metadata or {}
        iteration = metadata.get("explanation_iteration", 0)

        # --------------------
        # Layer 1: summarize and assess beliefs
        # --------------------        
        print(f"[{self.name}] Invoke layer 1...belief revision")

        PHASE_KEYS = {
            "dataprep": "explanation",
            "modelling": "evaluation",
            "reviewing": "judgement",
        }

        reasoning_state = {}

        for phase, key in PHASE_KEYS.items():
            summary_prompt = PROMPTS["summary_prompt"].format(
                item1=metadata.get(key, {}),
                item2=None,
                item3=None,
            )
            reasoning_state[phase] = self.llm(summary_prompt)

        # Now assess the belief
        belief_prompt = PROMPTS["belief_prompt"].format(reasoning_summary = reasoning_state)
        belief_assessment, unc_explanation_layer1 = self.llm(belief_prompt, return_uncertainty=True)
        belief_assessment_text = extract_analysis(belief_assessment)
        belief_score = self._extract_score(belief_assessment)

        print(belief_assessment)
        print(belief_score)

        # --------------------
        # Layer 2: TCAV
        # --------------------   
        print(f"[{self.name}] Invoke layer 2...TCAV assessment")

        # Get all agent outputs from metadata
        agent_texts = {
            "dataprep1": [metadata.get("plan_dataprep", "")],
            "dataprep2": [metadata.get("verification", "")],
            "dataprep3": [metadata.get("explanation", "")],
            "modelling1": [metadata.get("plan_modelling", "")],
            "modelling2": [metadata.get("evaluation", "")],
            "modelling3": [metadata.get("impact_analysis", "")],
            "reviewing1": [metadata.get("layer1_out", "")],
            "reviewing2": [metadata.get("analysis", "")],
            "reviewing3": [metadata.get("consistency_check", "")],
            "reviewing4": [metadata.get("judgement", "")]
        }

        # run TCAV analysis
        tcav_table =run_tcav_analysis(
            llm_wrapper=self.hub.shared_llm,
            texts=agent_texts,
            concept_file="utils/tcav_concepts.txt",
            random_file="utils/random_concepts.txt",
            layers_to_test=[16, 20, 24],
            store_dir="data/evaluation/tcav_plots",
        )

        tcav_prompt = PROMPTS["tcav_prompt"].format(tcav_table=tcav_table)
        tcav_assessment, unc_explanation_layer2 = self.llm(tcav_prompt, return_uncertainty=True)
        tcav_assessment_text = extract_analysis(tcav_assessment)
        tcav_score = self._extract_score(tcav_assessment)

        print(tcav_assessment)
        print(tcav_score)
        
        # --------------------
        # Layer 3: fairness assessment
        # --------------------  
        print(f"[{self.name}] Invoke layer 3...fairness assessment")

        df_predictions = self.load_latest_prediction_df()
        table_age, table_density = group_fairness(df_predictions, 'Prediction', 'ClaimNb', 'data/audit')

        fairness_prompt = PROMPTS["fairness_prompt"].format(table_age=table_age, table_density=table_density)
        fairness_assessment, unc_explanation_layer3 = self.llm(fairness_prompt, return_uncertainty=True)
        fairness_assessment_text = extract_analysis(fairness_assessment)
        fairness_score = self._extract_score(fairness_assessment)

        print(fairness_assessment)
        print(fairness_score)

        # --------------------
        # Layer 4: decision
        # --------------------  
        print(f"[{self.name}] Invoke layer 4...final assessment")

        final_prompt = PROMPTS["decision_prompt"].format(
            belief_assessment=belief_assessment_text,
            tcav_assessment=tcav_assessment_text,
            fairness_assessment=fairness_assessment_text,
            belief_score=belief_score,
            tcav_score=tcav_score,
            fairness_score=fairness_score
        )
        final_evaluation, unc_explanation_layer4 = self.llm(final_prompt, return_uncertainty=True)
        final_evaluation_text = extract_analysis(final_evaluation)

        decision = self._extract_decision(final_evaluation)

        # Routing
        next_action = ROUTING_MAP_EXPLANATION.get(decision, "consult_actuary")

        print(f"[{self.name}] Decision → {decision}, Routing → {next_action}")

        # --------------------
        # Layer 5: finalize
        # --------------------  
        if decision in ["approve", "minor_issues", "abort"]:
            print(f"[{self.name}] Invoke layer 5...create final explanation report")
            report_prompt = PROMPTS["report_prompt"].format(
                final_evaluation=final_evaluation_text,
                decision=decision)
            recommendations = None
            final_report = self.llm(report_prompt)
        else:
            print(f"[{self.name}] Invoke layer 5...create revision recommendations")
            recommendation_prompt = PROMPTS["recommendation_prompt"].format(
                final_evaluation=final_evaluation,
                decision=decision)
            recommendations = self.llm(recommendation_prompt)
            final_report = None

        print(recommendations)

        # --------------------
        # Save metadata
        # --------------------
        print(f"[{self.name}] Saving metadata...")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        # Store review report
        report_path = f"data/evaluation/explanation_report_{timestamp}.txt"
        generate_explanation_report_txt(report_path, final_report, belief_assessment_text, tcav_assessment_text, fairness_assessment_text, final_evaluation_text)

        # Store metadata
        metadata = {
            "timestamp": timestamp,
            "belief_assessment": belief_assessment,
            "belief_score": belief_score,
            "tcav_assessment": tcav_assessment,
            "tcav_score": tcav_score,
            "fairness_assessment": fairness_assessment,
            "fairness_score": fairness_score,
            "final_evaluation": final_evaluation,
            "decision": decision,
            "action": next_action,
            "recommendations": recommendations,
            "final_report": final_report,
            "unc_explanation_layer1": 1-unc_explanation_layer1,
            "unc_explanation_layer2": 1-unc_explanation_layer2,
            "unc_explanation_layer3": 1-unc_explanation_layer3,
            "unc_explanation_layer4": 1-unc_explanation_layer4, 
            "explanation_iteration": iteration + 1
        }

        results_dir = "data/results"
        os.makedirs(results_dir, exist_ok=True)
        meta_path = os.path.join(results_dir, f"{self.name}_metadata_{timestamp}.json")
        save_json_safe(metadata, meta_path)
        metadata["metadata_file"] = meta_path

        # Log to central memory
        if self.hub and self.hub.memory:
            self.hub.memory.log_event(self.name, "workflow_explanation", metadata)
            past_explanations = self.hub.memory.get("explanation_history", [])
            past_explanations.append(metadata)
            self.hub.memory.update("explanation_history", past_explanations)

        # Return message to the hub
        return Message(
            sender=self.name,
            recipient="hub",
            type="response",
            content=f"Generated explanations. Decision: {decision}.",
            metadata=metadata,
        )

